# Generated by Django 3.2.6 on 2021-08-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio',
            field=models.ManyToManyField(blank=True, to='stocks.Stock'),
        ),
    ]
