# Generated by Django 3.2.6 on 2021-08-30 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='', max_length=10)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=200)),
                ('website', models.URLField()),
                ('currency', models.CharField(max_length=5)),
                ('current_quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.price')),
                ('historic', models.ManyToManyField(related_name='stocks_historic', to='stocks.Price')),
            ],
        ),
    ]
