# Generated by Django 3.2.6 on 2021-08-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='historic',
            field=models.ManyToManyField(blank=True, related_name='stocks_historic', to='stocks.Price'),
        ),
    ]
