# Generated by Django 3.2.6 on 2021-09-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_stock_historic'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='limit_inferior',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stock',
            name='limit_superior',
            field=models.FloatField(default=0.0),
        ),
    ]
