# Generated by Django 3.2.6 on 2021-09-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20210901_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='limit_inferior',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='limit_superior',
            field=models.FloatField(default=-1.0),
        ),
    ]
