# Generated by Django 3.2.6 on 2021-09-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20210901_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='trend',
            field=models.CharField(default='neutral', max_length=5),
        ),
    ]
