# Generated by Django 3.2.6 on 2021-09-02 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_stock_trend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='data',
            new_name='date',
        ),
    ]
