# Generated by Django 3.2.6 on 2021-09-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_alter_stock_trend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='trend',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
