# Generated by Django 3.2.6 on 2021-09-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_alter_stock_trend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='trend',
            field=models.TextField(default='-'),
        ),
    ]
